---
title: "Internal consistency"
author: "Jana Jung"
date: "15 1 2025"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "C:/Users/jana/PycharmProjects/Master_Thesis/src")
```



```{r packages message=FALSE}
# load packages
library(tidyverse)
library(haven)
library(psych)
library(sirt)
library(glue)
```



```{r}
# load ASI data
file_ASI <- "Mistral-7B-Instruct-v0.3__persona_hub__ASI__2025-02-07_23-32"

############ ASI ############
# dolphin-2.8-mistral-7b-v02__chatbot_arena_conv__ASI__2025-02-10_05-13
# dolphin-2.8-mistral-7b-v02__persona_hub__ASI__2025-02-10_07-42

# Llama-3.1-8B-Instruct__chatbot_arena_conv__ASI__2025-02-06_00-05
# Llama-3.1-8B-Instruct__persona_hub__ASI__2025-02-07_11-05

# Mistral-7B-Instruct-v0.3__chatbot_arena_conv__ASI__2025-02-07_09-21 
# Mistral-7B-Instruct-v0.3__persona_hub__ASI__2025-02-07_23-32

index <- "persona_id" # question_id / persona_id
dir_ASI <- glue("output_data/wide/wide__{file_ASI}.csv")

ASI <- read.csv(dir_ASI, header=TRUE, row.names=index)
```


```{r}
# load MSS data
file_MSS <- "Mistral-7B-Instruct-v0.3__persona_hub__MSS__2025-02-07_17-36"

############ MSS ############
# dolphin-2.8-mistral-7b-v02__chatbot_arena_conv__MSS__2025-02-09_22-34
# dolphin-2.8-mistral-7b-v02__persona_hub__MSS__2025-02-09_22-41

# Llama-3.1-8B-Instruct__chatbot_arena_conv__MSS__2025-02-07_23-00
# Llama-3.1-8B-Instruct__persona_hub__MSS__2025-02-07_22-12

# Mistral-7B-Instruct-v0.3__chatbot_arena_conv__MSS__2025-02-07_19-47
# Mistral-7B-Instruct-v0.3__persona_hub__MSS__2025-02-07_17-36

dir_MSS <- glue("output_data/wide/wide__{file_MSS}.csv")

MSS <- read.csv(dir_MSS, header=TRUE, row.names=index) # uses same index as ASI
```


```{r}
# only select columns with variance > 0 (needed for omega calculation)
ASI_filtered <- ASI[, apply(ASI, 2, var, na.rm = TRUE) > 0]
MSS_filtered <- MSS[, apply(MSS, 2, var, na.rm = TRUE) > 0]

```


# Internal consistency

## ASI

### Cronbach's alpha (stratified)

```{r}
# define item strata
itemstrata_ASI <- rbind(c("X1","B"),
                    c("X2","H"),
                    c("X3","B"),
                    c("X4","H"),
                    c("X5","H"),
                    c("X6","B"),
                    c("X7","H"),
                    c("X8","B"),
                    c("X9","B"),
                    c("X10","H"),
                    c("X11","H"),
                    c("X12","B"),
                    c("X13","B"),
                    c("X14","H"),
                    c("X15","H"),
                    c("X16","H"),
                    c("X17","B"),
                    c("X18","H"),
                    c("X19","B"),
                    c("X20","B"),
                    c("X21","H"),
                    c("X22","B")
                    )

# calculate stratified Cronbach's alpha
stratified.cronbach.alpha(ASI, itemstrata = itemstrata_ASI)
```


### McDonald's omega

```{r}
omega(ASI_filtered, flip = FALSE)
```





## MSS

### Cronbach's alpha

```{r}
alpha(MSS)
```


### McDonald's omega

```{r}
omega(MSS_filtered, flip = FALSE)
```




# Convergent validity

```{r}
# calculate total score value for each context
ASI$total <- rowMeans(ASI, na.rm = TRUE)
MSS$total <- rowMeans(MSS, na.rm = TRUE)

```

```{r}
# calculate correlation (pearson)
cor(ASI$total, MSS$total)


```




